version: 2.1

executors:
  default:
    docker:
    - image: circleci/node:12.8.1
    working_directory: ~/task-management/client

commands:
  checkout_home:
    steps:
    - checkout:
        path: ~/task-management

jobs:
  client_test:
    executor: default
    steps:
    - checkout_home

    # Restore cache
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    # Install dependencies
    - run:
        name: Install Dependencies
        command: yarn

    # Keep cache
    - save_cache:
        paths:
        - "node_modules"
        key: v1-dependencies-{{ checksum "package.json" }}

    # Run lint
    - run:
        name: Run yarn lint
        command: yarn lint

    # Run test
    - run:
        name: Run yarn test
        command: yarn test:coverage

    # Sore coverage
    - store_artifacts:
        path: ~/task-management/coverage

workflows:
  build_and_test:
    jobs:
    - client_test
